### ISSUE TITLE
Preview v5 crashes with MODULE_NOT_FOUND error for worker.js

### ISSUE THREAD

**Issue by mkosir** [resendlabs/react-email#2687]
### Describe the Bug

After upgrading react-email from v4 to v5.x, the email preview server crashes 
when trying to render email templates.

**Command:**
`pnpm dev:email (email dev --port 3100 --dir src/features/email/templates)`

**Error:**
```sh
> email dev --port 3100 --dir src/features/email/templates

    React Email 5.0.4
    Running preview at:          http://localhost:3100

  ✔ Ready in 0.2s

  ⠹ Rendering email template CreditVoucherEmail.tsx

shutting down dev server
Error: Cannot find module '[absolute-project-path]/src/features/email/templates/user/lib/worker.js'
    at ignore-listed frames {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
  ✖ Rendering email template CreditVoucherEmail.tsx
```

**Environment:**
- "@react-email/components": "1.0.1",
- "@react-email/render": "2.0.0",
- "@react-email/preview-server": "5.0.5",
- "react-email": "5.0.5",
- pnpm 10.23.0

### Which package is affected (leave empty if unsure)

@react-email/preview

### To Reproduce

- Preview server starts successfully at http://localhost:3100
- When selecting any of the templates server immediately shuts down
- Fails with MODULE_NOT_FOUND for a worker.js file that doesn't exist

### Expected Behavior

When clicking and of the template, preview should render it.

### What's your node version? (if relevant)

24.11.1

**Comment by mkosir** [comment]
Closing the issue, found the cause
React Email's preview server uses esbuild to bundle templates. When templates imports pino logger, pino tries to spawn worker threads for pino-pretty transport. Esbuild can't bundle these worker files, causing the error `Cannot find module '.../lib/worker.js'`
